plugins {
	id 'dev.architectury.loom' version '1.7-SNAPSHOT'
	id 'maven-publish'
}

archivesBaseName = project.archives_base_name
version = "$project.mod_version+mc${project.minecraft_version}"
group = project.maven_group

repositories {
	maven {
		name = 'NeoForged'
		url = 'https://maven.neoforged.net/releases'
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings loom.layered {
		it.mappings("net.fabricmc:yarn:$project.yarn_mappings:v2")
		it.mappings("dev.architectury:yarn-mappings-patch-neoforge:$project.yarn_patch")
	}
	neoForge "net.neoforged:neoforge:$project.neoforge_version"

	api "blue.endless:jankson:1.2.3"
	include "blue.endless:jankson:1.2.3"
}

processResources {
	inputs.property "version", project.version

	filesMatching("META-INF/neoforge.mods.toml") {
		expand "version": project.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 21
}

java {
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}

jar {
	//baseName = "Jankson"
	from "LICENSE"
	manifest.attributes([
			"FMLModType": "LIBRARY"
	])
}

// configure the maven publication
publishing {
	publications {
		mavenJava(MavenPublication) {
			from components.java
		}
	}

	// select the repositories you want to publish to
	repositories {
		maven {
			name = "cloudsmith"
			url = "https://maven.cloudsmith.io/thinkingstudio/cottonjanksonfoxified/"
			def releasesRepoUrl = "https://maven.cloudsmith.io/thinkingstudio/cottonjanksonfoxified/"
			def snapshotsRepoUrl = "https://maven.cloudsmith.io/thinkingstudio/cottonjanksonfoxified/"
			url = version.endsWith('SNAPSHOT') ? snapshotsRepoUrl : releasesRepoUrl
			credentials {
				username = 'tex-true'
				password = System.getenv("CLOUDSMITH_MAVEN_TOKEN")
			}
		}
	}
}
