plugins {
	id 'dev.architectury.loom' version '1.7-SNAPSHOT'
	id 'maven-publish'
}

archivesBaseName = project.archives_base_name
version = "$project.mod_version+mc${project.minecraft_version}"
group = project.maven_group

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings "net.fabricmc:yarn:$project.yarn_mappings:v2"
	forge "net.minecraftforge:forge:$project.minecraft_version-$project.forge_version"

	api "blue.endless:jankson:1.2.3"
	include "blue.endless:jankson:1.2.3"
}

processResources {
	inputs.property "version", project.version

	filesMatching("META-INF/mods.toml") {
		expand "version": project.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 17
}

java {
	withSourcesJar()

	toolchain.languageVersion = JavaLanguageVersion.of(17)

	sourceCompatibility = JavaVersion.VERSION_17
	targetCompatibility = JavaVersion.VERSION_17
}

jar {
	//baseName = "Jankson"
	from "LICENSE"
	manifest.attributes([
			"FMLModType": "LIBRARY"
	])
}

// configure the maven publication
publishing {
	publications {
		mavenJava(MavenPublication) {
			from components.java
		}
	}

	// select the repositories you want to publish to
	repositories {
		maven {
			name = "cloudsmith"
			url = "https://maven.cloudsmith.io/thinkingstudio/cottonjanksonfoxified/"
			def releasesRepoUrl = "https://maven.cloudsmith.io/thinkingstudio/cottonjanksonfoxified/"
			def snapshotsRepoUrl = "https://maven.cloudsmith.io/thinkingstudio/cottonjanksonfoxified/"
			url = version.endsWith('SNAPSHOT') ? snapshotsRepoUrl : releasesRepoUrl
			credentials {
				username = 'tex-true'
				password = System.getenv("CLOUDSMITH_MAVEN_TOKEN")
			}
		}
	}
}
