# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
loom.platform = forge

# Fabric Properties
	# check these on https://fabricmc.net/use
	minecraft_version=1.20.1
	yarn_mappings=1.20.1+build.10
	yarn_patch = 1.21+build.4
	forge_version = 47.3.33

# Mod Properties
	mod_version = 6.0.0+j1.2.3
	maven_group = io.github.cottonmc
	archives_base_name = Jankson
