# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
loom.platform = neoforge

# Fabric Properties
	# check these on https://fabricmc.net/use
	minecraft_version=1.21.1
	yarn_mappings=1.21.1+build.3
	yarn_patch = 1.21+build.4
	neoforge_version = 21.1.122

# Mod Properties
	mod_version = 8.0.0+j1.2.3
	maven_group = org.thinkingstudio.jankson
	archives_base_name = JanksonFoxified
