modLoader = "javafml"
loaderVersion = "[46,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "cotton_jackson"
version = "${version}"
displayName = "CottonJanksonFoxified"
displayURL = "https://github.com/ThinkingStudios/CottonJanksonFoxified"
credits = "Falkreon, The Cotton Project"
authors = "TexTrue, ThinkingStudio"
description = '''
CottonMC's Jankson-Fabric unofficial (Neo)Forge port.

A (neo)forge-mod wrapper for Jankson, packaged with helpful (neo)forge-specific deserializers!
'''
logoFile = "assets/jankson/icon.png"

[[dependencies.cotton_jackson]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cotton_jackson]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"
